name: Sync to personal repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Push to personal GitHub repo
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_REPO_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git remote add personal https://HaiQuan21:${GH_TOKEN}@github.com/HaiQuan21/PhyGen-FE.git
          git push personal --force --all
          git push personal --force --tags
